import { AirtableRecord } from '../types/airtable';

// Demo property data for when Airtable credentials are not available
export const demoRecords: AirtableRecord[] = [
  {
    id: 'rec1',
    fields: {
      title: 'Luxury 3BHK Apartment',
      summary: 'Spacious luxury apartment with modern amenities and premium finishes in prime location.',
      bhk_type: '3BHK',
      property_type: 'Apartment',
      area_sqft: 1850,
      location: 'Bandra West, Mumbai',
      status: 'Available',
      furnished_status: 'Fully Furnished',
      price_estimate: '₹2.8 Cr',
      amenities: ['Swimming Pool', 'Gym', 'Parking', 'Security', 'Garden'],
      highlights: ['Sea View', 'Premium Location', 'Ready to Move'],
      screenshot_refs: [{ url: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80' }],
    },
    createdTime: '2024-01-15T10:30:00.000Z',
  },
  {
    id: 'rec2',
    fields: {
      title: 'Modern 2BHK Villa',
      summary: 'Contemporary villa with garden and excellent connectivity to major business districts.',
      bhk_type: '2BHK',
      property_type: 'Villa',
      area_sqft: 1200,
      location: 'Whitefield, Bangalore',
      status: 'Under Construction',
      furnished_status: 'Semi Furnished',
      price_estimate: '₹1.5 Cr',
      amenities: ['Clubhouse', 'Children Play Area', 'Jogging Track', 'Power Backup'],
      highlights: ['Gated Community', 'Green Surroundings', 'IT Hub Proximity'],
      screenshot_refs: [{ url: 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=800&q=80' }],
    },
    createdTime: '2024-01-14T14:20:00.000Z',
  },
  {
    id: 'rec3',
    fields: {
      title: 'Premium 4BHK Penthouse',
      summary: 'Luxurious penthouse with panoramic city views and top-tier amenities.',
      bhk_type: '4BHK',
      property_type: 'Penthouse',
      area_sqft: 3200,
      location: 'Cyber City, Gurgaon',
      status: 'Available',
      furnished_status: 'Fully Furnished',
      price_estimate: '₹4.2 Cr',
      amenities: ['Private Terrace', 'Home Theater', 'Wine Cellar', 'Concierge'],
      highlights: ['Sky Lounge', 'Premium Finishes', 'Smart Home Features'],
      screenshot_refs: [{ url: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80' }],
    },
    createdTime: '2024-01-13T09:15:00.000Z',
  },
  {
    id: 'rec4',
    fields: {
      title: 'Cozy 1BHK Studio',
      summary: 'Compact yet comfortable studio apartment perfect for young professionals.',
      bhk_type: '1BHK',
      property_type: 'Studio',
      area_sqft: 650,
      location: 'Koramangala, Bangalore',
      status: 'Sold',
      furnished_status: 'Unfurnished',
      price_estimate: '₹85 L',
      amenities: ['Elevator', 'Security', 'Power Backup', 'Gym'],
      highlights: ['Metro Connectivity', 'IT Hub', 'Shopping Centers Nearby'],
      screenshot_refs: [{ url: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=800&q=80' }],
    },
    createdTime: '2024-01-12T16:45:00.000Z',
  },
  {
    id: 'rec5',
    fields: {
      title: 'Spacious 5BHK Bungalow',
      summary: 'Independent bungalow with large garden and traditional architecture.',
      bhk_type: '5BHK',
      property_type: 'Bungalow',
      area_sqft: 4500,
      location: 'Juhu, Mumbai',
      status: 'Available',
      furnished_status: 'Semi Furnished',
      price_estimate: '₹8.5 Cr',
      amenities: ['Private Garden', 'Servant Quarters', 'Parking for 4 Cars', 'Swimming Pool'],
      highlights: ['Beach Proximity', 'Prime Location', 'Independent House'],
      screenshot_refs: [{ url: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=800&q=80' }],
    },
    createdTime: '2024-01-11T11:30:00.000Z',
  },
  {
    id: 'rec6',
    fields: {
      title: 'Modern 2BHK Flat',
      summary: 'Well-designed flat with excellent amenities and strategic location.',
      bhk_type: '2BHK',
      property_type: 'Flat',
      area_sqft: 1100,
      location: 'Sector 62, Noida',
      status: 'Available',
      furnished_status: 'Fully Furnished',
      price_estimate: '₹1.2 Cr',
      amenities: ['Club House', 'Swimming Pool', 'Gym', 'Children Play Area'],
      highlights: ['Metro Station Nearby', 'Shopping Mall', 'School Proximity'],
    },
    createdTime: '2024-01-10T08:20:00.000Z',
  },
];