import { AirtableRecord } from '../types/airtable';

// Demo property data for when Airtable credentials are not available
export const demoRecords: AirtableRecord[] = [
  {
    id: 'rec1',
    fields: {
      title: 'Luxury 3BHK Apartment in Prime Location',
      summary: 'Spacious luxury apartment with modern amenities and premium finishes. Features panoramic city views, high-end fixtures, and smart home integration. Perfect for families seeking comfort and style.',
      bhk_type: '3BHK',
      property_type: 'Apartment',
      area_sqft: 1850,
      location: ['Bandra West', 'Mumbai', 'Maharashtra'],
      status: 'Available',
      furnished_status: 'Fully Furnished',
      price_estimate: '₹2.8 - 3.2 Cr',
      amenities: ['Swimming Pool', 'Gymnasium', 'Covered Parking', '24x7 Security', 'Landscaped Garden', 'Clubhouse'],
      highlights: ['Sea View', 'Premium Location', 'Ready to Move', 'RERA Approved'],
      screenshot_refs: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80',
    },
    createdTime: '2024-01-15T10:30:00.000Z',
  },
  {
    id: 'rec2',
    fields: {
      title: 'Modern 2BHK Villa with Garden',
      summary: 'Contemporary designed villa featuring spacious rooms, private garden, and excellent connectivity. Built with eco-friendly materials and energy-efficient systems.',
      bhk_type: '2BHK',
      property_type: 'Villa',
      area_sqft: 1200,
      location: ['Whitefield', 'Bangalore', 'Karnataka'],
      status: 'Under Construction',
      furnished_status: 'Semi Furnished',
      price_estimate: '₹1.5 - 1.8 Cr',
      amenities: ['Clubhouse', 'Children Play Area', 'Jogging Track', 'Power Backup', 'Waste Management'],
      highlights: ['Gated Community', 'Green Surroundings', 'IT Hub Proximity', 'Metro Connectivity'],
      screenshot_refs: 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=800&q=80',
    },
    createdTime: '2024-01-14T14:20:00.000Z',
  },
  {
    id: 'rec3',
    fields: {
      title: 'Premium 4BHK Penthouse',
      summary: 'Luxurious penthouse offering panoramic city views and top-tier amenities. Features private terrace, smart home automation, and premium interior finishes.',
      bhk_type: '4BHK',
      property_type: 'Penthouse',
      area_sqft: 3200,
      location: ['Cyber City', 'Gurgaon', 'Haryana'],
      status: 'Available',
      furnished_status: 'Fully Furnished',
      price_estimate: '₹4.2 - 4.8 Cr',
      amenities: ['Private Terrace', 'Home Theater', 'Wine Cellar', 'Concierge Service', 'Valet Parking'],
      highlights: ['Sky Lounge', 'Premium Finishes', 'Smart Home Features', 'Helicopter Landing'],
      screenshot_refs: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80',
    },
    createdTime: '2024-01-13T09:15:00.000Z',
  },
  {
    id: 'rec4',
    fields: {
      title: 'Cozy 1BHK Studio for Professionals',
      summary: 'Compact yet comfortable studio apartment designed for young professionals. Features modern amenities, high-speed internet, and co-working spaces.',
      bhk_type: '1BHK',
      property_type: 'Studio',
      area_sqft: 650,
      location: ['Koramangala', 'Bangalore', 'Karnataka'],
      status: 'Sold',
      furnished_status: 'Unfurnished',
      price_estimate: '₹85 L - 95 L',
      amenities: ['High Speed Elevator', '24x7 Security', 'Power Backup', 'Fitness Center'],
      highlights: ['Metro Connectivity', 'IT Hub', 'Shopping Centers Nearby', 'Co-working Space'],
      screenshot_refs: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=800&q=80',
    },
    createdTime: '2024-01-12T16:45:00.000Z',
  },
  {
    id: 'rec5',
    fields: {
      title: 'Spacious 5BHK Independent Bungalow',
      summary: 'Large independent bungalow with traditional architecture, private garden, and ample parking. Perfect for joint families seeking space and privacy.',
      bhk_type: '5BHK',
      property_type: 'Bungalow',
      area_sqft: 4500,
      location: ['Juhu', 'Mumbai', 'Maharashtra'],
      status: 'Available',
      furnished_status: 'Semi Furnished',
      price_estimate: '₹8.5 - 9.2 Cr',
      amenities: ['Private Garden', 'Servant Quarters', 'Multi-car Parking', 'Swimming Pool', 'Security System'],
      highlights: ['Beach Proximity', 'Prime Location', 'Independent House', 'Celebrity Neighborhood'],
      screenshot_refs: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=800&q=80',
    },
    createdTime: '2024-01-11T11:30:00.000Z',
  },
  {
    id: 'rec6',
    fields: {
      title: 'Modern 2BHK Flat in Tech Hub',
      summary: 'Well-designed flat with excellent amenities and strategic location near major tech companies. Features modern interiors and sustainable living options.',
      bhk_type: '2BHK',
      property_type: 'Flat',
      area_sqft: 1100,
      location: ['Sector 62', 'Noida', 'Uttar Pradesh'],
      status: 'Available',
      furnished_status: 'Fully Furnished',
      price_estimate: '₹1.2 - 1.4 Cr',
      amenities: ['Club House', 'Swimming Pool', 'Gymnasium', 'Children Play Area', 'Solar Panels'],
      highlights: ['Metro Station Nearby', 'Shopping Mall', 'School Proximity', 'Tech Park Access'],
      screenshot_refs: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=800&q=80',
    },
    createdTime: '2024-01-10T08:20:00.000Z',
  },
];